# Generated by Django 4.1.2 on 2022-10-21 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postage_type', models.CharField(max_length=100)),
                ('rate', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Postages',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='UserAccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('address_line1', models.CharField(max_length=150)),
                ('address_line2', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=50)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('contact_email', models.EmailField(max_length=50)),
                ('weekly_package_count', models.CharField(choices=[('1', '1-10'), ('2', '11-50'), ('3', '51-200'), ('4', '200+')], max_length=50)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('your_branch', models.CharField(blank=True, max_length=50, null=True)),
                ('is_agree', models.BooleanField()),
                ('product_type', models.TextField()),
                ('promotional_code', models.CharField(max_length=50)),
                ('hear_about_us', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Account Details',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=150)),
                ('address2', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('has_postage', models.BooleanField()),
                ('shipment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('package_content', models.CharField(max_length=100)),
                ('retail_value', models.IntegerField()),
                ('currency', models.CharField(choices=[('1', 'CAD'), ('2', 'USD'), ('3', 'EUR')], max_length=50)),
                ('package_weight', models.IntegerField()),
                ('package_weight_unit', models.CharField(choices=[('1', 'lbs'), ('2', 'kg'), ('3', 'g'), ('4', 'oz')], max_length=50)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('package_length', models.IntegerField()),
                ('package_width', models.IntegerField()),
                ('package_height', models.IntegerField()),
                ('package_size_unit', models.CharField(choices=[('1', 'in'), ('2', 'cm')], max_length=50)),
                ('is_agree', models.BooleanField()),
                ('shipment_code', models.CharField(blank=True, max_length=50, null=True)),
                ('tracking_code', models.CharField(blank=True, max_length=50, null=True)),
                ('postage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.postage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shipments',
            },
        ),
        migrations.CreateModel(
            name='PickupDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=150)),
                ('address2', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('is_default', models.BooleanField(blank=True, null=True)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('instruction', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pickup details',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
    ]
