# Generated by Django 4.1.2 on 2022-10-21 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccountdetails',
            name='your_branch',
        ),
        migrations.AddField(
            model_name='useraccountdetails',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.branch'),
        ),
        migrations.AlterField(
            model_name='useraccountdetails',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.region'),
        ),
    ]
