# Generated by Django 4.1.2 on 2022-10-21 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_useraccountdetails_your_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountdetails',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branch'),
        ),
        migrations.AlterField(
            model_name='useraccountdetails',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region'),
        ),
    ]
