# Generated by Django 4.1.2 on 2022-10-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_useraccountdetails_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountdetails',
            name='has_active_ups_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccountdetails',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraccountdetails',
            name='is_agree',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
