# Generated by Django 4.1.2 on 2022-10-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_useraccountdetails_has_active_ups_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountdetails',
            name='is_agree',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='useraccountdetails',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
