# Generated by Django 4.1.2 on 2022-11-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_shipment_address1_alter_shipment_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
