# Generated by Django 4.1.2 on 2022-11-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_shipment_is_completed_shipment_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountdetails',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraccountdetails',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useraccountdetails',
            name='promotional_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
