# Generated by Django 4.1.2 on 2022-11-10 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_shippinguser_shipment_recipient_shipment_shipper'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippinguser',
            options={'verbose_name_plural': 'Shipping Users'},
        ),
        migrations.AddField(
            model_name='shipment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
