# Generated by Django 4.1.2 on 2022-11-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_shippinguser_options_shipment_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shipper',
        ),
        migrations.AddField(
            model_name='shipment',
            name='package_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
