# Generated by Django 4.1.2 on 2022-11-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_shipment_recipient_remove_shipment_shipper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='currency',
            field=models.CharField(blank=True, choices=[('CAD', 'CAD'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='package_size_unit',
            field=models.CharField(blank=True, choices=[('in', 'in'), ('cm', 'cm')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='package_weight_unit',
            field=models.CharField(blank=True, choices=[('lbs', 'lbs'), ('kg', 'kg'), ('g', 'g'), ('oz', 'oz')], max_length=50, null=True),
        ),
    ]
