# Generated by Django 4.1.2 on 2022-11-17 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_shipment_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postage',
            name='id',
        ),
        migrations.AlterField(
            model_name='postage',
            name='postage_type',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='postage_type',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.postage'),
        ),
    ]
