# Generated by Django 4.1.2 on 2022-11-22 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_shipmentimport'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PackageTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.packagetype')),
            ],
        ),
        migrations.AlterField(
            model_name='shipment',
            name='package_type',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.packagetype'),
        ),
    ]
