# Generated by Django 4.1.2 on 2022-11-22 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_packagetype_packagetypeoption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagetypeoption',
            name='id',
        ),
        migrations.AlterField(
            model_name='packagetypeoption',
            name='package_type',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='api.packagetype'),
        ),
        migrations.AlterField(
            model_name='packagetypeoption',
            name='title',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
