# Generated by Django 4.1.2 on 2022-11-22 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_packagetypeoption_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='package_type_option',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.packagetypeoption'),
        ),
    ]
