# Generated by Django 4.1.2 on 2022-11-22 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_shipment_package_type_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.AlterModelOptions(
            name='packagetype',
            options={'verbose_name_plural': 'Package Types'},
        ),
        migrations.AlterModelOptions(
            name='packagetypeoption',
            options={'verbose_name_plural': 'Package Type Options'},
        ),
        migrations.AddField(
            model_name='useraccountdetails',
            name='return_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.address'),
        ),
    ]
