# Generated by Django 4.1.2 on 2022-11-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_address_alter_packagetype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='postage_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
