# Generated by Django 4.1.2 on 2022-11-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_shipment_postage_rate_shipment_shipment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
    ]
