# Generated by Django 4.1.2 on 2022-11-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_shipment_shipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('paypal', 'Paypal')], max_length=50, null=True),
        ),
    ]
