# Generated by Django 4.1.2 on 2022-11-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_shipment_payment_id_shipment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
