# Generated by Django 4.1.2 on 2022-11-28 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
