# Generated by Django 4.1.2 on 2022-11-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_batch_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='country',
            field=models.CharField(default='Canada', max_length=50),
            preserve_default=False,
        ),
    ]
