# Generated by Django 4.1.2 on 2022-12-02 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0025_alter_shipment_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_id',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.CreateModel(
            name='PrepPackShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=10)),
                ('tracking_number', models.CharField(max_length=20)),
                ('package_description', models.CharField(blank=True, max_length=200, null=True)),
                ('service_type', models.CharField(max_length=50)),
                ('service_type_option', models.CharField(blank=True, max_length=50, null=True)),
                ('prep_instruction', models.CharField(blank=True, max_length=200, null=True)),
                ('package_weight', models.IntegerField(blank=True, null=True)),
                ('package_weight_unit', models.CharField(blank=True, choices=[('kg', 'kg'), ('lbs', 'lbs')], max_length=50, null=True)),
                ('package_length', models.IntegerField(blank=True, null=True)),
                ('package_width', models.IntegerField(blank=True, null=True)),
                ('package_height', models.IntegerField(blank=True, null=True)),
                ('package_dimensions_unit', models.CharField(blank=True, choices=[('in', 'in'), ('cm', 'cm')], max_length=50, null=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('has_shipment', models.BooleanField(default=False)),
                ('price_with_shipment', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('price_without_shipment', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=300, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('paypal', 'Paypal')], max_length=10, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.shipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Prep Pack & Ship',
            },
        ),
    ]
