# Generated by Django 4.1.2 on 2022-12-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_batch_batch_id_preppackship'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='preppackship',
            name='service_type',
            field=models.CharField(max_length=100),
        ),
    ]
