# Generated by Django 4.1.2 on 2022-12-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_shipment_is_deleted_alter_preppackship_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountdetails',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
