# Generated by Django 4.1.2 on 2023-01-10 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0028_alter_useraccountdetails_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=150)),
                ('address2', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('is_default', models.BooleanField(blank=True, null=True)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('instruction', models.TextField(blank=True, null=True)),
                ('package_weight', models.IntegerField(blank=True, null=True)),
                ('package_weight_unit', models.CharField(blank=True, choices=[('kg', 'kg'), ('lbs', 'lbs')], max_length=50, null=True)),
                ('package_length', models.IntegerField(blank=True, null=True)),
                ('package_width', models.IntegerField(blank=True, null=True)),
                ('package_height', models.IntegerField(blank=True, null=True)),
                ('package_dimensions_unit', models.CharField(blank=True, choices=[('in', 'in'), ('cm', 'cm')], max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('shipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.shipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pickups',
            },
        ),
        migrations.DeleteModel(
            name='PickupDetail',
        ),
    ]
