# Generated by Django 4.1.2 on 2023-02-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_pickup_delete_pickupdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_cross_border',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='package_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
