# Generated by Django 4.1.2 on 2023-02-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_shipment_is_cross_border_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='postage_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
