# Generated by Django 4.1.2 on 2023-09-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_pickup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='preppackship',
            name='is_packed',
            field=models.BooleanField(default=False),
        ),
    ]
