# Generated by Django 4.1.2 on 2023-09-14 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_preppackship_is_packed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='user',
        ),
    ]
