# Generated by Django 4.1.2 on 2023-11-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_blogdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='main_title',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='tab',
            field=models.CharField(choices=[('Blog Home', 'tab1'), ('News & Announcements', 'tab2'), ('Ecommerce Tips', 'tab3'), ('Shipping & Fulfillment', 'tab4'), ('Marketplace Strategies', 'tab5'), ('Customer Spotlights', 'tab6')], default='tab1', max_length=50),
        ),
    ]
