# Generated by Django 4.1.2 on 2023-11-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_blogdetail_main_title_blogdetail_tab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='tab',
            field=models.CharField(choices=[('tab1', 'Blog Home'), ('tab2', 'News & Announcements'), ('tab3', 'Ecommerce Tips'), ('tab4', 'Shipping & Fulfillment'), ('tab5', 'Marketplace Strategies'), ('tab6', 'Customer Spotlights')], default='tab1', max_length=50),
        ),
    ]
